server:
  port: 9090

spring:
  application:
    name: gateway-monevo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: user_auth
              uri: ${USER_AUTH_URL:http://localhost:8080}
              predicates:
                - Path=/monevo/auth/**

            - id: wallet
              uri: ${WALLET_URL:http://localhost:8082}
              predicates:
                - Path=/monevo/wallet/**

            - id: market_data
              uri: ${MARKET_DATA_URL:http://localhost:8081}
              predicates:
                - Path=/consulta-cotacao/**
