server:
  port: 8083

spring:
  application:
    name: monevo-trading

  datasource:
    url: jdbc:postgresql://localhost:5432/trading_monevo
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  market-data:
    url: ${MARKET_DATA_URL:http://localhost:8081}

  wallet:
    url: ${WALLET_URL:http://localhost:8082}
    username: trading
    password: ${TRADING_SERVICE_PASSWORD}

jwt:
  key: ${JWT_KEY}
